### ISSUE TITLE
Provide some basic information for plugin development

### ISSUE THREAD

**Issue by semaph0r** [Norman0406/LISA#1]
It would be cool to reference some additional ressources (blog, tutorials, how-tos, ...) within the wiki regarding to Qt's plugin architecture and how it is used (adopted) developing plugins for LISA.

Furthermore point out some design guidelines which will prevent us from cluttered source code.

**Comment by Norman0406** [comment]
Right now I don't have much time to write an extensive documentation. My priority at this time lies in pushing the development further as fast as I can besides my regular job. However, I will extend the wiki with basic information as soon as possible.
If you want to begin developing a new plugin for lisa, you can start by copying the "digital" plugin and renaming everything to the name of the new plugin. Add a reference to the plugin QBS file to "plugins.qbs". When everything builds successfully, the plugin is loaded automatically.
Here is some additional information about the digital plugin:
- DigitalPlugin: the main plugin class that does all the plugin-related initialization
- DigitalMode: a mode is displayed in the bar on the left with an icon
- DigitalWindow: the main window displayed within the mode

There is also an example plugin called "helloworld" that can provide additional information about the plugin infrastructure. As soon has you have a prototypical (mostly empty) plugin, just issue a pull request and I will have a look into it.

**Comment by Norman0406** [comment]
There is now a simple empty plugin available to begin the development of a logbook plugin. This is the most minimalistic plugin in this context. Development uses the standard Qt principles. Some tips:
- Use signals/slots when needed, and standard QWidgets (no QML etc. please).
- There are different threading concepts for different use cases. Use the appropriate one to keep the gui responsive.
- Remember the Qt memory management and garbage collection system and cleanup your own memory that is not managed by Qt.
- KISS

Try not to spend too much time with the wiki. We will work on it when the time comes. By now, just start coding and have fun :)
If there are any questions whatsoever, just write me.
